# Generated by Django 4.2.5 on 2023-09-28 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('members', models.JSONField()),
                ('owner', models.CharField(max_length=100)),
                ('creation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=100)),
                ('creation_date', models.DateField()),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chatroom')),
            ],
        ),
    ]
