# Generated by Django 4.2.5 on 2023-10-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
