# Generated by Django 4.2.5 on 2023-10-03 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_chatroom_creation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('members', models.JSONField()),
                ('owner', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField()),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.deletedchatroom')),
            ],
        ),
    ]
